version: '3'

services:
  nginx:
    build: docker/nginx
    ports:
      - 80:80
    volumes:
      - ./sources/public:/var/www/public

  php-fpm:
    build: docker/php-fpm
    working_dir: /var/www
    volumes:
      - ./sources:/var/www
      - /home/gregory/.composer:/.composer

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=gnut
      - MYSQL_PASSWORD=iebooz9U
      - MYSQL_DATABASE=accounts