cart_display:
    path: /
    methods: GET
    controller: App\Application\Controller\Cart\DisplayCart

cart_update:
    path: /
    methods: POST
    controller: App\Application\Controller\Cart\AddItemToCart
